### ISSUE TITLE
How to use slick-joda-mapper with injected play.api.db.slick.DatabaseConfigProvider ? 

### ISSUE THREAD

**Issue by dragisak** [tototoshi/slick-joda-mapper#38]
I'd like to use dependency injection to make my choice of database configurable. In other words, I don't want to hard code the database by doing something like 
```scala
import com.github.tototoshi.slick.H2JodaSupport._
```

However, the example in the readme does not work with the latest  Play 2.4.x, Slick 3.1.0 and slick-joda-mapper 2.1.0

```scala
import javax.inject.Inject
import com.github.tototoshi.slick.GenericJodaSupport
import org.joda.time.DateTime
import play.api.db.slick.DatabaseConfigProvider
import slick.driver.JdbcProfile

class MyRepository @Inject()(dbConfigProvider: DatabaseConfigProvider) {

  val dbConfig = dbConfigProvider.get[JdbcProfile]
  import dbConfig.driver.api._

  // Incompatible types !!
  // dbConfig.driver is an instance of JdbcProfile, not JdbcDriver
  private object PortableJodaSupport extends GenericJodaSupport(dbConfig.driver)

  import PortableJodaSupport._

  class MyTable(tag: Tag) extends Table[(Long, String, DateTime)](tag, "my_table") {
     def id = column[Long]("id", O.PrimaryKey)
     def name = column[String]("name")
     def time = column[DateTime]("date_time")
     def * = (id, name, time)
  }
  // ...
}
```

I don't see an elegant way to get hold of Slick driver. Ugly workaround would be to read the configuration and try to find the Slick driver object in the classpath.

**Comment by ehudkaldor** [comment]
+1
any fixes?

**Comment by Driky** [comment]
just tried to use slick-joda-mapper for the first time and spent 3h chasing my tail because of this one =P Hope a fix is in the making.

**Comment by rayronvictor** [comment]
I do this by casting the ``dbConfig.driver``.

```scala
trait TablesDefinitions extends Tables {

  import driver.api._

  object PortableJodaSupport extends GenericJodaSupport(driver.asInstanceOf[JdbcDriver])
  import PortableJodaSupport._


  /**
   * Tabela que representa os usuários do sistema.
   */
  class UsersTable(tag: Tag) extends IdTable[User](tag, "usuario") {

    def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def name = column[String]("nome")
    def lastName = column[String]("sobrenome")
    def email = column[String]("email")
    def phoneNumber = column[String]("telefone")
    def institution = column[String]("instituicao")
    def institutionPosition = column[String]("cargo")
    def pictureUrl = column[String]("foto_url")
    def activated = column[Boolean]("ativo")

    // apenas um usuário por email
    def idx_email = index("unique_email", email, unique = true)

    // projeção
    def * = (id.?, name, lastName, email, phoneNumber, institution, institutionPosition, pictureUrl, activated) <> ((User.apply _).tupled, User.unapply)
  }


  /**
   * Tabela que representa um tipo de login
   */
  class DBLoginInfoTable(tag: Tag) extends IdTable[DBLoginInfo](tag, "login_info") {
    ...
  }
  ...
}

trait Tables extends HasDatabaseConfigProvider[JdbcProfile] {

  import driver.api._

  /**
   * Representa as tabelas que tem identificador.
   * @tparam I tipo do identificador
   */
  trait TableWithId[I] {
    def id: Rep[I]
  }

  /**
   * Representa uma tabela com um identificador.
   */
  abstract class IdTable[M <: Identifiable[M]](tag: Tag, schemaName: Option[String], tableName: String)(implicit val colType: BaseColumnType[M#Id])
    extends Table[M](tag, schemaName, tableName) with TableWithId[M#Id] {

    def this(tag: Tag, tableName: String)(implicit mapping: BaseColumnType[M#Id]) = this(tag, None, tableName)
  }

}


```

**Comment by tototoshi** [comment]
I don't know much about play-slick but maybe this is because of the change that play-slick switch to use JdbcProfile instead of JdbcDriver. JdbcDriver is now marked as deprecated.

I published 2.2.0-SNAPSHOT to sonatype snapshot repository. please try it.

**Comment by dragisak** [comment]
What Play does is equivalent to using `DatabaseConfig` like:

```scala
val dbConfig = DatabaseConfig.forConfig[JdbcProfile]("mydb", config)
import dbConfig.driver.api._
```

The goal is to make choice of database driver configurable and avoid hardcoding database.

**Comment by Driky** [comment]
Any advice for someone new to scala and play ?

I normally do this :
```scala
protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile](current)
  import dbConfig._
  import dbConfig.driver.api._
  import com.github.tototoshi.slick.PostgresJodaSupport._
```

**Comment by dragisak** [comment]
@Driky You had to explicitly import `PostgresJodaSupport` although your choice of database, PsotgreSQL or some else, is set in `application.conf`.  This ticket is about joda-mapper being able to, in similar way that Slick does, figure out which database mapper to use based only on configuration.

**Comment by d1egoaz** [comment]
What if you use:
```
import driver.api._
import com.github.tototoshi.slick.JdbcJodaSupport._
```

**Comment by dragisak** [comment]
`JdbcJodaSupport` doesn't exist in the current release of slick-joda-mapper

**Comment by Driky** [comment]
By the way thx @dragisak your solution worked !

**Comment by jmcclell** [comment]
@tototoshi Any word on the status of getting a stable 2.2 release for the switch to JdbcProfile from JdbcDriver? Do you have anything you need completed/tested/working before you release?

**Comment by tototoshi** [comment]
@jmcclell Released 2.2.0. Please try it.
